# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pinit < Formula
  desc ""
  homepage ""
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/enuesaa/pinit/releases/download/v0.0.7/pinit_0.0.7_darwin_amd64.tar.gz"
      sha256 "2e02033d4ffcbaa1a33c0d72e4863e3d6ec47f7a0235c0560440dec9155e6310"

      def install
        bin.install "pinit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/enuesaa/pinit/releases/download/v0.0.7/pinit_0.0.7_darwin_arm64.tar.gz"
      sha256 "43c403494575a8a9fb5fdbe9f324e7ff3e4c18721a66d02c171c4fad3c1d66d4"

      def install
        bin.install "pinit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/enuesaa/pinit/releases/download/v0.0.7/pinit_0.0.7_linux_arm64.tar.gz"
      sha256 "85e3e0a0d1d9ab0e439675c65e351e7784e31e81a846d50cae88d8e599f85510"

      def install
        bin.install "pinit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/enuesaa/pinit/releases/download/v0.0.7/pinit_0.0.7_linux_amd64.tar.gz"
      sha256 "c72a6e38ba0237cd57c3dfb872978ef4e5a8bb086f9d3baab390244ed84e94d9"

      def install
        bin.install "pinit"
      end
    end
  end
end
