services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - 9113:9113
    entrypoint: nginx-prometheus-exporter -nginx.scrape-uri=http://nginx/status
    depends_on:
      - nginx

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - nginx-prometheus-exporter

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    volumes:
      - grafanadata:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafanadata:
