-- generated by chatgpt
--
--

-- 1. Hello, World!
print("Hello, World!")

-- 2. 変数とデータ型
local num = 42       -- 数値
local str = "Lua!"   -- 文字列
local bool = true    -- ブール値
print(num, str, bool)

-- 3. 条件分岐
local age = 20
if age < 18 then
    print("未成年です")
else
    print("成人です")
end

-- 4. ループ (for)
for i = 1, 5 do
    print("カウント: ", i)
end

-- 5. ループ (while)
local count = 0
while count < 5 do
    print("ループ中: ", count)
    count = count + 1
end

-- 6. 関数
local function greet(name)
    return "こんにちは、" .. name .. "さん！"
end
print(greet("太郎"))

-- 7. テーブル (配列として使用)
local fruits = {"りんご", "みかん", "バナナ"}
for i, fruit in ipairs(fruits) do
    print("フルーツ " .. i .. ": " .. fruit)
end

-- 8. テーブル (連想配列として使用)
local person = {
    name = "花子",
    age = 25
}
print("名前: " .. person.name .. ", 年齢: " .. person.age)

-- 9. メタテーブル
local t = {x = 10}
local mt = {
    __index = function(table, key)
        return key == "y" and 20 or nil
    end
}
setmetatable(t, mt)
print("x: " .. t.x .. ", y: " .. t.y)

-- 10. コルーチン
local co = coroutine.create(function()
    for i = 1, 3 do
        print("コルーチン内: ", i)
        coroutine.yield()
    end
end)
coroutine.resume(co)
coroutine.resume(co)
coroutine.resume(co)

-- 11. ファイル操作
local file = io.open("test.txt", "w")
file:write("これは Lua のファイル操作例です。\n")
file:close()

-- 12. エラーハンドリング
local function divide(a, b)
    if b == 0 then
        error("ゼロで割ることはできません")
    end
    return a / b
end

local status, result = pcall(divide, 10, 0)
if status then
    print("結果: ", result)
else
    print("エラー: ", result)
end
