# NOTE: generated by chatgpt.

# --- 1. 出力 ---
puts "Hello, Ruby!"
puts("Hello, Ruby!") # メソッドの引数が一つだけなら括弧は省略できる


# --- 2. 変数と型 ---
name = "Alice"
age = 25
height = 1.65
puts "名前: #{name}, 年齢: #{age}, 身長: #{height}m"
puts sprintf("名前: %s, 年齢: %d, 身長: %.2fm", name, age, height)


# --- 3. 条件分岐 ---
if age >= 20
  puts "成人です。"
else
  puts "未成年です。"
end


# --- 4. 配列と繰り返し ---
fruits = ["りんご", "みかん", "バナナ"]
fruits.each do |fruit|
  puts "好きな果物: #{fruit}"
end


# --- 5. ハッシュ ---
person = {
  name: "Alice",
  age: 25,
  city: "東京",
}
puts "名前: #{person[:name]}, 年齢: #{person[:age]}, 都市: #{person[:city]}"


# --- 6. メソッド ---
def greet(name)
  return "こんにちは、#{name}さん！"
end
puts greet("太郎")


# --- 7. クラスとオブジェクト ---
class Person
  attr_accessor :name, :age

  def initialize(name, age)
    @name = name
    @age = age
  end

  def introduce
    "私の名前は#{@name}で、#{@age}歳です。"
  end
end

person = Person.new("花子", 30)
puts person.introduce


# --- 8. 例外処理 ---
begin
  result = 10 / 0
rescue ZeroDivisionError
  puts "エラー: 0で割ることはできません。"
end


# --- 9. モジュール ---
module MathHelper
  def self.add(a, b)
    a + b
  end
end
puts "5 + 3 = #{MathHelper.add(5, 3)}"


# --- 10. 標準ライブラリ ---
# see https://docs.ruby-lang.org/en/master/standard_library_rdoc.html
require 'date'
today = Date.today
puts "今日の日付: #{today}"
