services:
  redis:
    image: redis/redis-stack
    ports:
      - 6379:6379
      - 8001:8001 # redis insight
    volumes:
      - redisdata:/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrantdata:/qdrant/storage
  # see http://localhost:6333/dashboard

volumes:
  redisdata:
  qdrantdata:
