// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function Greet2(arg1) {
  return window['go']['main']['App']['Greet2'](arg1);
}

export function MakeSomeDir() {
  return window['go']['main']['App']['MakeSomeDir']();
}
