// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHomeDir():Promise<string>;

export function Greet2(arg1:string):Promise<string>;

export function MakeSomeDir():Promise<void>;
