services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    volumes:
      - grafanadata:/var/lib/grafana
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:latest
    command: [--config.file=/etc/tempo.yaml]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - 3200:3200

  collector:
    image: otel/opentelemetry-collector-contrib
    command: [--config=/etc/otel-collector.yaml]
    volumes:
      - ./collector.yaml:/etc/otel-collector.yaml
    ports:
      - 4318:4318
    depends_on:
      - tempo

volumes:
  grafanadata:
