services:
  metabase:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - MB_PASSWORD_COMPLEXITY=weak
    volumes:
      - metabasedb:/metabase.db
      - ./csv:/csv

volumes:
  metabasedb:
