---
- name: setup
  hosts: all 
  become: yes

  tasks:
    - ansible.builtin.apt:
        update_cache: yes
    
    - ansible.builtin.apt:
        name:
          - vim-common
          - vim-tiny
        purge: yes
        state: absent

    - ansible.builtin.apt:
        name:
          - wget
          - tar
          - vim
        state: present

    - ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/workdir'
        state: directory
        recurse: yes

    - ansible.builtin.get_url:
        url: https://go.dev/dl/go1.22.0.linux-arm64.tar.gz
        dest: '{{ ansible_env.HOME }}/workdir/go122.tar.gz'
        checksum: sha256:6a63fef0e050146f275bf02a0896badfe77c11b6f05499bb647e7bd613a45a10

    - ansible.builtin.unarchive:
        src: '{{ ansible_env.HOME }}/workdir/go122.tar.gz'
        dest: '/usr/local'
        remote_src: yes

    - ansible.builtin.lineinfile:
        path: '{{ ansible_env.HOME }}/.bashrc'
        line: 'export PATH=$PATH:/usr/local/go/bin'

    - ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/workdir'
        state: absent
