---
- name: setup
  hosts: all 
  become: true

  tasks:
    - include_tasks: tasks/common.yaml
    # - include_tasks: tasks/golang.yaml
    # - include_tasks: tasks/speakit.yaml
    - include_tasks: tasks/docker.yaml
