CREATE TABLE books (
  id        VARCHAR(25) PRIMARY KEY,
  title     TEXT NOT NULL,
  author_id VARCHAR(25),
  created   DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated   DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE authors (
  id      VARCHAR(25) PRIMARY KEY,
  name    VARCHAR(255) NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated DATETIME DEFAULT CURRENT_TIMESTAMP
);
