services:
  mongo:
    image: mongo:8.0.0-rc20
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    tty: true

  mongo-express:
    image: mongo-express:1
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=pass

volumes:
  mongodata:
