name: ci

on:
  push:
    branches:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - uses: pnpm/action-setup@v2
        with:
          version: '9'

      # ui
      - run: pnpm install
      - run: pnpm build
      
      # go
      - run: go test ./...
      - run: go install
