Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'bin/bundle'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'config/environments/production.rb'

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/environments/production.rb'

Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - 'Gemfile'

Metrics/BlockLength:
  Max: 26

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 13

Metrics/PerceivedComplexity:
  Max: 9

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/notes_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/notes_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
    - 'db/migrate/20240114103921_create_notes.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/application.rb'

Style/PerlBackrefs:
  Exclude:
    - 'bin/bundle'

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 10

Layout/LineLength:
  Max: 198
