services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rails
      TZ: Asia/Tokyo
    volumes:
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOSTS: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - 3001:80
    depends_on:
      - mysql

volumes:
  mysqldata: