source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 7.1.2"
gem "sqlite3", "~> 1.4"
gem "puma", ">= 5.0"
gem "bootsnap", require: false
gem "active_model_serializers"

group :development do
  gem "web-console"
  gem "rubocop", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
end

group :test do
end
