version: '3.8'

# see https://github.com/hkford/opentelemetry-go-sdk-deep-dive/blob/main/compose.yaml
services:
  collector:
    image: public.ecr.aws/aws-observability/aws-otel-collector
    ports:
      - 4317:4317
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - 14268:14268
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
