// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbq

import (
	"database/sql"
)

type Author struct {
	ID      string
	Name    string
	Created sql.NullTime
	Updated sql.NullTime
}

type Book struct {
	ID       string
	Title    string
	AuthorID sql.NullString
	Created  sql.NullTime
	Updated  sql.NullTime
}
