import { MouseEventHandler } from 'react'

export const Capture = () => {
  const handleClick: MouseEventHandler<HTMLButtonElement> = async (e) => {
    e.preventDefault()

    // code generated by chatgpt
  
    chrome.tabs.create({ url: 'https://example.com' }, (tab) => {
      chrome.tabs.onUpdated.addListener(function listener(tabId, changeInfo) {
        // if (tabId === tab.id && changeInfo.status === 'complete') {
          chrome.tabs.captureVisibleTab(null, {}, function (image) {
            chrome.downloads.download({
              url: image,
              filename: 'capture.png'
            });
          });
          chrome.tabs.onUpdated.removeListener(listener);
        // }
      });
    });
  };

  return <button onClick={handleClick}>capture</button>
}
